apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: sh-task-manager
spec:
  ports:
    - port: 80
  selector:
    app: sh-task-manager
    tier: application
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: sh-task-manager
spec:
  selector:
    matchLabels:
      app: sh-task-manager
      tier: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sh-task-manager
        tier: application
    spec:
      containers:
        - image: sh-task-manager-application
          name: application
          imagePullPolicy: Never
          env:
            - name: APP_PORT
              value: '80'
            - name: JWT_AUDIENCE
              value: http://localhost
            - name: JWT_ISSUER
              value: http://localhost/{ISSUER}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-pass
                  key: tokenSecret
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: db
            - name: DB_DATABASE
              value: app
            - name: DB_USERNAME
              value: mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: password
            - name: EMAIL_FROM
              value: notify@shtaskmapp.com
            - name: QUEUE_HOST
              value: rabbitmq
            - name: QUEUE_PORT
              value: '5672'
            - name: QUEUE_USERNAME
              value: myuser
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-pass
                  key: password
            - name: QUEUE_NOTIFY_NAME
              value: notify
          ports:
            - containerPort: 80
              name: application
