secretGenerator:
  - name: db-pass
    literals:
      - password=mypass
  - name: db-root-pass
    literals:
      - password=myrootpass
  - name: rabbit-pass
    literals:
      - password=mypassword
  - name: application-pass
    literals:
      - tokenSecret=appsupersecret
resources:
  - application-deployment.yml
  - consumer-deployment.yml
  - db-deployment.yml
  - adminer-deployment.yml
  - mailhog-deployment.yml
  - rabbitmq-deployment.yml
  - flyway-deployment.yml
