apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: sh-task-manager
spec:
  ports:
    - port: 15672
      name: rabbitmq-web
  selector:
    app: sh-task-manager
    tier: rabbitmq
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: sh-task-manager
spec:
  selector:
    matchLabels:
      app: sh-task-manager
      tier: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sh-task-manager
        tier: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.12-management-alpine
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-pass
                  key: password
            - name: RABBITMQ_DEFAULT_USER
              value: myuser
          ports:
            - containerPort: 15672
              name: rabbitmq-web
            - containerPort: 5672
              name: rabbitmq
